### ISSUE TITLE
Farsandra Maven Plugin

### ISSUE THREAD

**Issue by agazzarini** [edwardcapriolo/farsandra#13]
Hi @edwardcapriolo, as briefly discussed, I'd like to bring here a small contribution, a Farsandra maven plugin that I have at the moment in my account [1]. However, before creating the patch I have some questions: 

## Maven layout
The current Farsandra structure is a single maven module with jar packaging. The plugin is another module, I wouldn't merge its sources with the Farsandra core so my idea is the following: 

- forking your project, 
- inserting a top-level module (pom.xml packaging) 
- inserting two children: the current farsandra and the maven plugin
- providing a patch

So the resulting structure would be:

* farsandra (pom packaging)
  * farsandra-core (the current module, jar packaging )
  * farsandra-maven-plugin (maven plugin packaging)

What do you think? I'm asking because I don't know if there's a better, less invasive, choice or, if the "invasiveness" is not a problem :) 

## Maven repo
The current version of the plugin contains a com.github.github:site-maven-plugin for publishing the plugin artifact under a maven repository hosted in GitHub. I see that farsandra is already hosted in the central repo so I'm not sure if you need that.

**Comment by edwardcapriolo** [comment]
The concept of breaking into a multi-module project make sense. I am +1. The lifecycle of any good project is that eventually becomes a multi-module one.

**Comment by agazzarini** [comment]
Ok, so I'd proceed in this way: 

* A stable version of the maven plugin on my account
* Test of the plugin within another project in my account [1], so I'll be sure things are properly working 
* Fork of farsandra 
* Patch with the multi-module layout as described above

In this way we'll minimize the interval between the fork and the patch and (hopefully) the merge would be easier  

-------------------------
[1] https://github.com/agazzarini/cumulusrdf
