### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jancona** [edwardcapriolo/farsandra#25]
Could we get a release of the current master branch (8dcd997)? Thanks!

**Comment by edwardcapriolo** [comment]
What version of JDK are you running.

Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 sec
Running io.teknek.farsandra.TestFarsandraWithDefaultConfig
out Cassandra 2.0 and later require Java 7u25 or later.

[edward@jackintosh farsandra]$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Comment by edwardcapriolo** [comment]
Ok wait figuring it out might me maven profile issues. :) Still testing sorry for the delay

**Comment by jancona** [comment]
Let me know if you want me to check anything on my end.

**Comment by edwardcapriolo** [comment]
So I notice the custom conf stuff is failing. It may not have been your doing. I am fixing it now and I will add travis to this project soon. Still on it expect release by EOD.

**Comment by oscerd** [comment]
Is there something I broke in the past?
Il 24/feb/2016 21:02, "edwardcapriolo" <notifications@github.com> ha
scritto:

**Comment by edwardcapriolo** [comment]
Fixed here : https://github.com/edwardcapriolo/farsandra/commit/d81cd6f0049b6af6fda766da53f2044bfd80da90

**Comment by edwardcapriolo** [comment]
The issue is the ConfigHolder is looking for a $home/.test which is not populated in my env

**Comment by edwardcapriolo** [comment]
Released 0.0.9 https://oss.sonatype.org/content/repositories/ioteknek-1030/io/teknek/farsandra-core/0.0.9/

**Comment by edwardcapriolo** [comment]
Thanks for your help all.

**Comment by jancona** [comment]
Thanks!

**Comment by oscerd** [comment]
Maybe we can think to automate the release process

**Comment by edwardcapriolo** [comment]
Yes we can. The sonatype side is automatable by extra maven plugins. lets track that in a new ticket.
