### ISSUE TITLE
Authentication and Authorization

### ISSUE THREAD

**Issue by oscerd** [edwardcapriolo/farsandra#7]
Hi,

How we can add Authentication and Authorization inside a farsandra instance?

Is there something that is possible to use in the current version?

Maybe I can help to develop something.

Bye,
Andrea

**Comment by edwardcapriolo** [comment]
We should be able to use the current macros to re-write the yaml file.

    fs.withYamlReplacement("# NOTE:", "# deNOTE:");

That would allow us to do this:

authenticator: PasswordAuthenticator

The one challenge is farsandra does not know and does not want to know how to speak thrift/cql protocol. This is what allows us to keep all the ugly dependencies off the classpath. 

So executing statements like 'ALTER USER' is typically up to the user of farsandra inside their test cases.

**Comment by oscerd** [comment]
You're right.

I'm currently try to connect to a farsandra instance with Datastax Java Driver and farsandra uses PasswordAuthenticator and CassandraAuthorizer.

Thank you,
Andrea

**Comment by edwardcapriolo** [comment]
Interesting. Does that mean you have to change the authenticator to the AllowAllAuthenticator just to get going these days?

**Comment by oscerd** [comment]
Currently I'm working to some improvement to my Apache Camel component based on cassandra: https://github.com/oscerd/camel-cassandra

I'm working on the authentication and authorization by passing parameters (username and password) to the endpoint and I'm trying to test this new feature using Farsandra. I think it is a problem of configuration and not a Farsandra's problem.

```java
        String id = RandomStringUtils.random(12,
                "0123456789abcdefghijklmnopqrstuvwxyz");
        fs = new Farsandra();
        fs.withVersion("2.0.3");
        fs.withCleanInstanceOnStart(true);
        fs.withInstanceName("target" + File.separator + id);
        fs.withCreateConfigurationFiles(true);
        fs.withHost("localhost");
        fs.withSeeds(Arrays.asList("localhost"));
        fs.withYamlReplacement("authenticator: AllowAllAuthenticator", "authenticator: PasswordAuthenticator");
        fs.withYamlReplacement("authorizer: AllowAllAuthorizer", "authorizer: CassandraAuthorizer");
        final CountDownLatch started = new CountDownLatch(1);
        fs.getManager().addOutLineHandler(new LineHandler() {
            @Override
            public void handleLine(String line) {
                if (line.contains("Listening for thrift clients...")) {
                    started.countDown();
                }
            }
        });
        fs.getManager().addProcessHandler(new ProcessHandler() {
            @Override
            public void handleTermination(int exitValue) {
                started.countDown();
            }
        });
        fs.start();
        try {
            started.await();
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
```

Farsandra starts correctly, the problem arises when I try to connect to the instance with the Datastax Java Driver and it is right: on the instance I've configured Authentication Enabled, but there is no Authentication Provider in reality. I have to take care of this aspect programmatically and it's not so simple.

**Comment by oscerd** [comment]
Anyway I think testing authentication and authorization is not a Farsandra's purpose.
