### ISSUE TITLE
Release Farsandra 0.0.7

### ISSUE THREAD

**Issue by oscerd** [edwardcapriolo/farsandra#8]
Hi Edward,

When do you plan to release Farsandra 0.0.7?

Thank you.

**Comment by edwardcapriolo** [comment]
All tests pass. Preparing release.

**Comment by edwardcapriolo** [comment]
Message from: https://oss.sonatype.org



Deployer properties:

    "userAgent" = "Apache-Maven/3.0.4 (Java 1.7.0_13; Linux 3.9.10-100.fc17.x86_64)"
    "userId" = "ecapriolo"
    "ip" = "24.44.156.234"


Details:

The following artifacts have been staged

/io/teknek/farsandra/0.0.7/farsandra-0.0.7.jar.asc
(SHA1: 385f839350ca89c04235b083e9b5ad8665b7bdd9)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7.pom.asc
(SHA1: 7b24bd4f65be54aad1d5b68a602acbebc6cb23dc)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7-tests.jar.asc
(SHA1: ff5f45430f454d7aae4c50a664c629005dfef6cd)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7.pom
(SHA1: eb767e369765fd42467148898bcf462a65a558fe)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7-tests.jar
(SHA1: 521dc655748acea4130b92b896c943b4d6882f17)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7.jar
(SHA1: 1534064065635d41ae21569c4aa194916e4c25a6)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7-sources.jar.asc
(SHA1: d17372806c41a8203ec384329c496b9334421930)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7-javadoc.jar
(SHA1: 17da60940855c9d50460fbead967759592452460)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7-javadoc.jar.asc
(SHA1: bcec4305a07552bb446cb92c78f75f3b3b3d91dd)
/io/teknek/farsandra/0.0.7/farsandra-0.0.7-sources.jar
(SHA1: a598565c3e95e4482fc93413cad949d2c2790cb9)

**Comment by edwardcapriolo** [comment]
@oscerd Would you like to have commit + release capabilities for this project?

**Comment by oscerd** [comment]
Hi Edward,

Yes. It would be a pleasure for me. I think we can write a roadmap with features for the future and so on.

Thank you for having trust in me.

Andrea
