### ISSUE TITLE
Farsandra future development and improvements

### ISSUE THREAD

**Issue by oscerd** [edwardcapriolo/farsandra#9]
Hi everyone,

I think we can start a discussion about the future development of Farsandra.

What do you think?

Andrea

**Comment by edwardcapriolo** [comment]
I was thinking that farsandra can be broken off, there are several types of Java projects I would like to be able to launch in a managed fork. 

Farsandra specifics :I would like a better way (maybe like a shutdown hook sometimes processes hang open).

I would like a better way to detect thrift open, (maybe using a tcp check).

There is a feature request for tweaking the logger properties as well.

**Comment by oscerd** [comment]
If you need some help on other projects, consider me.

I can work on the improvements you listed on Farsandra.

**Comment by edwardcapriolo** [comment]
Great. Thanks for the offer! I am glad to have the help but do not feel obligated to work on anything you do not need unless it is something you want to do!
